### PR TITLE
Fix a test and type error

### PR DESCRIPTION
**Pull request by harryzcy**

### CODE REVIEW

**Comment by harryzcy** [comment]
@ghedo Are you willing to have a test workflow via GitHub Actions?

**Comment by gabivlj** [comment]
Thanks for the submission @harryzcy :). Yeah, you can submit a Github Actions test workflow if it's not too much trouble.

**Comment by harryzcy** [comment]
> Thanks for the submission @harryzcy :). Yeah, you can submit a Github Actions test workflow if it's not too much trouble.

Done.

**Comment by gabivlj** [comment]
Could you cherry-pick https://github.com/cloudflare/serverless-registry/compare/gv/fix-types?expand=1 and not add `// @ts-nocheck`?

**Comment by gabivlj** [comment]
I think that threads: false won't have an effect anymore. Testing locally and still seeing the same issue.

https://github.com/cloudflare/serverless-registry/compare/gv/fix-text?expand=1

Maybe this fixes it?

**Comment by harryzcy** [comment]
> I think that threads: false won't have an effect anymore. Testing locally and still seeing the same issue.
> 
> https://github.com/cloudflare/serverless-registry/compare/gv/fix-text?expand=1
> 
> Maybe this fixes it?

No. The issue only appears in Node 18, with the following log. See https://github.com/harryzcy/serverless-registry/actions/runs/8134428863/job/22227353338

```
✓ index.test.ts  (18 tests) 414ms
 Test Files  1 passed (1)
      Tests  18 passed (18)
   Start at  01:01:55
   Duration  11.27s (transform [24](https://github.com/harryzcy/serverless-registry/actions/runs/8134428863/job/22227353338#step:6:25)8ms, setup 0ms, collect [25](https://github.com/harryzcy/serverless-registry/actions/runs/8134428863/job/22227353338#step:6:26)6ms, tests 414ms, environment 257ms, prepare 72ms)
close timed out after 10000ms
Failed to terminate worker while running /home/runner/work/serverless-registry/serverless-registry/index.test.ts.
Tests closed successfully but something prevents Vite server from exiting
You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
```

**Comment by harryzcy** [comment]
@gabivlj I got more logs available through `hanging-process` reporter that maybe helpful. Do you have any idea why?

```
Test Files  1 passed (1)
      Tests  18 passed (18)
   Start at  01:15:48
   Duration  11.33s (transform 279ms, setup 0ms, collect 294ms, tests 406ms, environment 259ms, prepare 75ms)
There are 28 handle(s) keeping the process running
# Tinypool
node:internal/async_hooks:200                                                                                            
node:internal/async_hooks:503                                                                                            
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:[36](https://github.com/harryzcy/serverless-registry/actions/runs/8134541965/job/22227618141#step:6:37)              
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:57              
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:767             
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/vitest/dist/vendor-cli-api.8cf9[37](https://github.com/harryzcy/serverless-registry/actions/runs/8134541965/job/22227618141#step:6:38)e8.js:7211
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/vitest/dist/vendor-cli-api.8cf937e8.js:74[40](https://github.com/harryzcy/serverless-registry/actions/runs/8134541965/job/22227618141#step:6:41)
# WORKER
node:internal/async_hooks:200                                                                                            
node:internal/worker:207                                                                                                 
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:533             
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:518             
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:503             
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/tinypool/dist/esm/index.js:772             
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/vitest/dist/vendor-cli-api.8cf937e8.js:7211
file:///home/runner/work/serverless-registry/serverless-registry/node_modules/vitest/dist/vendor-cli-api.8cf937e8.js:7[44](https://github.com/harryzcy/serverless-registry/actions/runs/8134541965/job/22227618141#step:6:45)0
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
# FILEHANDLE
node:internal/async_hooks:200
close timed out after [100](https://github.com/harryzcy/serverless-registry/actions/runs/8134541965/job/22227618141#step:6:101)00ms
Failed to terminate worker while running /home/runner/work/serverless-registry/serverless-registry/index.test.ts.
Tests closed successfully but something prevents Vite server from exiting
You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
```

**Comment by harryzcy** [comment]
@gabivlj It's passing in Github actions in my fork now: https://github.com/harryzcy/serverless-registry/actions/runs/8134722107

It seems to be the issue with older version of vitest. I merged in the main branch, and it now seems to be fine.

**Comment by gabivlj** [comment]
Nice :). Thanks for the contribution. Squashing and merging the PR.

**Pull request merged**
