### PR TITLE
Remove upload leftovers on PUT request

### PR DESCRIPTION
**Pull request by IvanDev**
This PR removes upload state file from R2 on single-chunk multipart uploads.

### CODE REVIEW

**Review by gabivlj — CHANGES_REQUESTED** [review]
Can you instead remove this line and this one and put in a single place the removal? (outside the if else block basically)

https://github.com/cloudflare/serverless-registry/blob/a554e90a01bcb7ce4d6a84f99d981b1fa378a4b0/src/registry/r2.ts#L625

**Comment by gabivlj** [comment]
Thank you for the submission! I have one suggestion but the changes look good to me 👍

**Comment by IvanDev** [comment]
Sure!

**Review by gabivlj — APPROVED** [review]
Amazing thank you!

**Pull request merged**
